### ISSUE TITLE
Error of invalid syntax in line 82?

### ISSUE THREAD

**Issue by rdiaz02** [parchd-1/qutebrowser-zotero#1]
When I try to run either of
`spawn --userscript zotero`

or

`hint links userscript zotero` [and then, I select a link]

I get  the error 

```
Process stderr:
File "/home/ramon/.local/share/qutebrowser/userscripts/zotero", line 82
    print('message-info "{}"'.format(message), file=fifo)
                                                   ^
SyntaxError: invalid syntax
```

Looking at the code, I understand this is just notify_error being called but I have no clue about what I am doing wrong.

I am running Zotero v. 5.0.37 in Debian.

**Comment by The-Compiler** [comment]
That looks like it's running with Python 2 - the shebang of the script should probably say `python3`.

**Comment by rdiaz02** [comment]
Thanks! Using `python3` fixes the problem when calling
`spawn --userscript zotero`

But now, using 
`hint links userscript zotero`

I get the error

```
Process stderr:
Traceback (most recent call last):
  File "/home/ramon/.local/share/qutebrowser/userscripts/zotero", line 126, in <module>
    main()
  File "/home/ramon/.local/share/qutebrowser/userscripts/zotero", line 95, in main
    r = get(url, headers={"User-Agent": e["QUTE_USER_AGENT"]})
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'QUTE_USER_AGENT'
```

I guess this is probably some minor thing, but I don't know how to solve it.

**Comment by The-Compiler** [comment]
`QUTE_USER_AGENT` is only set for userscripts when it's customized (via `:set content.headers.user_agent` in qutebrowser) - so that seems like a bug in the script.

**Comment by rdiaz02** [comment]
OK, so the problem is probably in line

`r = get(url, headers={"User-Agent": e["QUTE_USER_AGENT"]})`

but I have no idea what to use instead of "QUTE_USER_AGENT". I've tried (blindly) different things, to no avail.
